# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'Open Disclosure California: Static!'
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  An experiment rendering the Open Disclosure website as a static Jekyll site.
baseurl: "/odca-jekyll" # the subpath of your site, e.g. /blog
url: "https://adborden.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adborden
github_username:  adborden
future: true
permalink: pretty


collections:
  ballots:
    output: true
    permalink: /election/:path/
  candidates:
    output: true
    permalink: /candidate/:path/
  committees:
    output: true
    permalink: /committee/:path/
  localities:
    output: true
    permalink: /:path/
  referendums:
    output: true
    permalink: /referendum/:path/
  referendum_opposing:
    output: true
    permalink: /referendum/:path/opposing/
  referendum_supporting:
    output: true
    permalink: /referendum/:path/supporting/

defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      type: ballots
    values:
      layout: ballot
  - scope:
      type: candidates
    values:
      layout: candidate
  - scope:
      type: committees
    values:
      layout: committee
  - scope:
      type: localities
    values:
      layout: locality
  - scope:
      type: referendums
    values:
      layout: referendum
  - scope:
      type: referendum_opposing
    values:
      layout: referendum_opposing
  - scope:
      type: referendum_supporting
    values:
      layout: referendum_supporting


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
